export const ADD_NEW_VALUE = 'ADD_NEW_VALUE';

export const GET_ITEM_LIST_PENDING = 'GET_ITEM_LIST_PENDING';
export const GET_ITEM_LIST_SUCCESS = 'GET_ITEM_LIST_SUCCESS';
export const GET_ITEM_LIST_ERROR = 'GET_ITEM_LIST_ERROR';